### ISSUE TITLE
Portrait rework is broken with zoom level

### ISSUE THREAD

**Issue by Miketaviuos** [Crapsky233/DialogueTweak#6]
The new portrait display rework has broken the dialog. Doesn't seem to respect zoom levels of the player. Also players end up showing up in the portrait as well as other players, pets, summons pretty much everything. **There should be a config option to switch back from how it previously was and how it is now.**

https://github.com/Cyrillya/DialogueTweak/assets/122772498/129e42c5-420d-4b5e-8fc3-5aa7a497eb95

**Comment by Cyrillya** [comment]
> **There should be a config option to switch back from how it previously was and how it is now.**

Well there is an option to switch it back. Just open config and turn on the third option called **Display NPC Chat Portrait as Bestiary Portrait**. It's not exactly same as the previous version but should fix your issue.

> Also players end up showing up in the portrait as well as other players, pets, summons pretty much everything.

Sadly I am unable to fix this

> Doesn't seem to respect zoom levels of the player

This is a bug that will be fixed

**Comment by Cyrillya** [comment]
Updated and fixed zooming issues, though there might be mod conflicts that break it again.

If the issue persists, post a list of mods you enabled here
