### ISSUE TITLE
[Suggestion] Add a config option to disable the chat output when clicking the happiness icon.

### ISSUE THREAD

**Issue by Foozey** [Crapsky233/DialogueTweak#8]
Please add an option to disable this: 
![image](https://github.com/Cyrillya/DialogueTweak/assets/68371808/f307a194-38e6-4894-bf64-6cac72e4c71b)

Also, both the "static" and the "bestiary" options don't seem to work for me:
![image](https://github.com/Cyrillya/DialogueTweak/assets/68371808/0ce0f84c-f95e-4514-a600-3ce410cd726e)

Finally, if you want to fix it, the robot from Magic Storage has the wrong icon for "Help"
![image](https://github.com/Cyrillya/DialogueTweak/assets/68371808/d0f06f78-8f15-4833-b4ef-8088151ecc8c)

**Comment by Cyrillya** [comment]
Add your log files so that I can track the issue
The compatibility issue from Magic Storage **should be fixed on their side**, just as all the other mods do

**Comment by Cyrillya** [comment]
And there's already a config option for this a year ago

No further info provided + useless suggestion, therefore closed

**Comment by Foozey** [comment]
This option disables the happiness icons as well. I want an option to **only** disable the chat output.
![image](https://github.com/Cyrillya/DialogueTweak/assets/68371808/aadcf736-d52a-4b63-9687-b78d0ae6f8bf)

As for the missing NPC images, here's the client.log:
[client.log](https://github.com/user-attachments/files/15911457/client.log)
